(function(){
var PID='9697dfd9af83db5aac112e59884411dd';
var BHEX='0x2105';
var RPC='https://mainnet.base.org';
window.zyWallet={address:null,provider:null,signer:null,connected:false,onConnect:null};
var css=document.createElement('style');
css.textContent='.zy-ov{position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,.85);z-index:100000;display:none;justify-content:center;align-items:center;backdrop-filter:blur(10px)}.zy-ov.active{display:flex}.zy-m{background:#0d1117;border:1px solid #1a2a1a;padding:32px;max-width:420px;width:92%;position:relative;font-family:"Share Tech Mono",monospace}.zy-x{position:absolute;top:12px;right:16px;background:none;border:none;color:#606060;font-size:24px;cursor:pointer}.zy-x:hover{color:#00ff88}.zy-m h3{font-family:"Orbitron",sans-serif;font-size:14px;color:#00ff88;letter-spacing:3px;margin-bottom:20px}.zy-o{display:flex;align-items:center;gap:14px;padding:14px 16px;border:1px solid #1a2a1a;margin-bottom:6px;cursor:pointer;transition:all .3s;background:#0d1a12}.zy-o:hover{border-color:#00ff88;background:#0f2218}.zy-oi{font-size:22px;width:36px;text-align:center}.zy-on{font-size:12px;letter-spacing:2px;color:#c0c0c0}.zy-od{font-size:9px;color:#606060;margin-top:2px}.zy-s{font-size:10px;color:#00e5ff;letter-spacing:1px;margin-top:12px;text-align:center}.zy-dl{margin-top:16px}.zy-dl a{display:block;padding:14px 16px;border:1px solid #1a2a1a;margin-bottom:6px;background:#0d1a12;text-decoration:none;color:#c0c0c0;font-family:"Share Tech Mono",monospace;font-size:11px;letter-spacing:1px;transition:all .3s}.zy-dl a:hover{border-color:#00ff88;color:#00ff88}';
document.head.appendChild(css);
var ov=document.createElement('div');ov.className='zy-ov';ov.id='zyM';
ov.innerHTML='<div class="zy-m"><button class="zy-x" onclick="zyClose()">&times;</button><div id="zyC"><h3>CONNECT WALLET</h3><div class="zy-o" onclick="zyInj(\'mm\')"><div class="zy-oi">🦊</div><div><div class="zy-on">METAMASK</div><div class="zy-od">Browser extension or mobile</div></div></div><div class="zy-o" onclick="zyWC()"><div class="zy-oi">🔗</div><div><div class="zy-on">WALLETCONNECT</div><div class="zy-od">Open in mobile wallet</div></div></div><div class="zy-o" onclick="zyInj(\'cb\')"><div class="zy-oi">🔵</div><div><div class="zy-on">COINBASE WALLET</div><div class="zy-od">Coinbase browser or mobile</div></div></div><div class="zy-s" id="zyS" style="display:none"></div></div></div>';
document.addEventListener('DOMContentLoaded',function(){document.body.appendChild(ov);ov.addEventListener('click',function(e){if(e.target===ov)zyClose()})});
window.zyOpen=function(){document.getElementById('zyM').classList.add('active');var c=document.getElementById('zyC');c.querySelector('h3').textContent='CONNECT WALLET';document.querySelectorAll('.zy-o').forEach(function(el){el.style.display='flex'});var dl=document.getElementById('zyDL');if(dl)dl.remove();var s=document.getElementById('zyS');if(s){s.style.display='none'}};
window.zyClose=function(){document.getElementById('zyM').classList.remove('active')};
function zyMsg(m){var el=document.getElementById('zyS');if(el){el.textContent=m;el.style.display='block'}}
function zyDone(addr){window.zyWallet.address=addr;window.zyWallet.connected=true;var sh=addr.slice(0,6)+'...'+addr.slice(-4);var cb=document.getElementById('connectBtn');var wa=document.getElementById('walletAddr');if(cb)cb.style.display='none';if(wa){wa.style.display='flex';wa.textContent=sh}zyClose();if(typeof window.zyWallet.onConnect==='function')window.zyWallet.onConnect(addr)}
async function zyBase(){if(!window.ethereum)return;try{await window.ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:BHEX}]})}catch(e){if(e.code===4902){await window.ethereum.request({method:'wallet_addEthereumChain',params:[{chainId:BHEX,chainName:'Base',nativeCurrency:{name:'ETH',symbol:'ETH',decimals:18},rpcUrls:[RPC],blockExplorerUrls:['https://basescan.org']}]})}}}
window.zyInj=async function(t){if(typeof window.ethereum==='undefined'){if(t==='mm')window.open('https://metamask.io/download/','_blank');else window.open('https://www.coinbase.com/wallet','_blank');return}zyMsg('REQUESTING ACCOUNT...');try{var a=await window.ethereum.request({method:'eth_requestAccounts'});if(a[0]){await zyBase();if(typeof ethers!=='undefined'){window.zyWallet.provider=new ethers.BrowserProvider(window.ethereum);window.zyWallet.signer=await window.zyWallet.provider.getSigner()}zyDone(a[0])}}catch(e){zyMsg('CONNECTION REJECTED');console.error(e)}};
window.zyWC=function(){document.querySelectorAll('.zy-o').forEach(function(el){el.style.display='none'});document.getElementById('zyC').querySelector('h3').textContent='OPEN IN WALLET';var dl=document.createElement('div');dl.id='zyDL';dl.className='zy-dl';dl.innerHTML='<a href="https://metamask.app.link/dapp/zylogen.xyz" target="_blank">🦊 OPEN IN METAMASK MOBILE</a><a href="https://go.cb-w.com/dapp?cb_url=https://zylogen.xyz" target="_blank">🔵 OPEN IN COINBASE WALLET</a><a href="https://link.trustwallet.com/open_url?coin_id=8453&url=https://zylogen.xyz" target="_blank">🛡️ OPEN IN TRUST WALLET</a><div style="margin-top:12px;font-size:9px;color:#606060;text-align:center;letter-spacing:1px">OPENS ZYLOGEN.XYZ INSIDE YOUR WALLET BROWSER</div><button onclick="zyOpen()" style="margin-top:12px;background:none;border:1px solid #1a2a1a;color:#606060;padding:8px 16px;font-family:Share Tech Mono,monospace;font-size:10px;letter-spacing:2px;cursor:pointer;width:100%">← BACK</button>';document.getElementById('zyC').appendChild(dl)};
window.openWallet=window.zyOpen;window.closeWallet=window.zyClose;window.connectWallet=window.zyOpen;window.connectMetaMask=function(){zyInj('mm')};window.connectCoinbase=function(){zyInj('cb')};window.connectWC=window.zyWC;
})();
